//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Craftian.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Craftian.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump Servers are servers that are preconfigured to work with the Craftian launcher to install and configure required mods automatically. This makes it much easier to join modded servers that require client mods. 
        ///
        ///When you join a Jump Server Craftian will download and install the required mods then launch Minecraft and directly connect you to the server you chose.
        ///
        ///If you are the owner of a modded Minecraft server and would like your server listed here please visit https://craftianmod.com/jump to learn  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string abt_JumpServers {
            get {
                return ResourceManager.GetString("abt_JumpServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Jump Servers.
        /// </summary>
        public static string abt_JumpServers_Title {
            get {
                return ResourceManager.GetString("abt_JumpServers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Login.
        /// </summary>
        public static string cBox_AutoLogin {
            get {
                return ResourceManager.GetString("cBox_AutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We seem to be having trouble reaching Mojang.
        /// </summary>
        public static string err_Connectivity_Mojang {
            get {
                return ResourceManager.GetString("err_Connectivity_Mojang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email...
        /// </summary>
        public static string plc_Email {
            get {
                return ResourceManager.GetString("plc_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password...
        /// </summary>
        public static string plc_Password {
            get {
                return ResourceManager.GetString("plc_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shellcode.
        /// </summary>
        public static string prog_Author {
            get {
                return ResourceManager.GetString("prog_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawlsec.
        /// </summary>
        public static string prog_Company {
            get {
                return ResourceManager.GetString("prog_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we login to your Mojang account...
        /// </summary>
        public static string prog_Login_Message {
            get {
                return ResourceManager.GetString("prog_Login_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging In.
        /// </summary>
        public static string prog_Login_Title {
            get {
                return ResourceManager.GetString("prog_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craftian.
        /// </summary>
        public static string prog_Name {
            get {
                return ResourceManager.GetString("prog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craftian Launcher.
        /// </summary>
        public static string prog_Name_Long {
            get {
                return ResourceManager.GetString("prog_Name_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop your mod on the &quot;Manage Mods&quot; button to install.
        /// </summary>
        public static string sb_DragDrop {
            get {
                return ResourceManager.GetString("sb_DragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop your mod to install.
        /// </summary>
        public static string sb_DragDropTarget {
            get {
                return ResourceManager.GetString("sb_DragDropTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to login to your Mojang account, please check your login details and retry..
        /// </summary>
        public static string str_FailedLogin_Message {
            get {
                return ResourceManager.GetString("str_FailedLogin_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string str_FailedLogin_Title {
            get {
                return ResourceManager.GetString("str_FailedLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string str_Login {
            get {
                return ResourceManager.GetString("str_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Mojang account details.
        /// </summary>
        public static string str_Login_Message {
            get {
                return ResourceManager.GetString("str_Login_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Minecraft.
        /// </summary>
        public static string str_Login_Title {
            get {
                return ResourceManager.GetString("str_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string str_Logout {
            get {
                return ResourceManager.GetString("str_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout of your Mojang account?.
        /// </summary>
        public static string str_Logout_Message {
            get {
                return ResourceManager.GetString("str_Logout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout of Minecraft.
        /// </summary>
        public static string str_Logout_Title {
            get {
                return ResourceManager.GetString("str_Logout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mojang Connection.
        /// </summary>
        public static string tt_Connection {
            get {
                return ResourceManager.GetString("tt_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Mods.
        /// </summary>
        public static string tt_ManageMods {
            get {
                return ResourceManager.GetString("tt_ManageMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft Version.
        /// </summary>
        public static string tt_Minecraft_Version {
            get {
                return ResourceManager.GetString("tt_Minecraft_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Minecraft.
        /// </summary>
        public static string tt_Play {
            get {
                return ResourceManager.GetString("tt_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Servers.
        /// </summary>
        public static string tt_Servers {
            get {
                return ResourceManager.GetString("tt_Servers", resourceCulture);
            }
        }
    }
}
